; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AEC Spot Revit 2020 - V1.0.0.0"
#define MyAppVersion "1.0.0.0"
#define MyAppPublisher "AEC Spot"
#define MyAppURL "www.AECSpot.com"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{34F6DBF6-8442-462C-8A93-7BEA395621EB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=.\Output
OutputBaseFilename={#MyAppName}

Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: ".\bin\Debug\*"; DestDir: "C:\Program Files (x86)\AECSpot\2020"; Flags: ignoreversion


Source: ".\Mainfist\AECSpot.addin"; DestDir: "C:\ProgramData\Autodesk\Revit\Addins\2020"; Flags: ignoreversion
Source: ".\Mainfist\AECSpot.addin"; DestDir: "C:\ProgramData\Autodesk\Revit\Addins\2021"; Flags: ignoreversion
Source: ".\Mainfist\AECSpot.addin"; DestDir: "C:\ProgramData\Autodesk\Revit\Addins\2022"; Flags: ignoreversion
Source: ".\Mainfist\AECSpot.addin"; DestDir: "C:\ProgramData\Autodesk\Revit\Addins\2023"; Flags: ignoreversion

Source: ".\Resources\*"; DestDir: "C:\Program Files (x86)\AECSpot\2020"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

